- hosts: all
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: Force apt to ipv4
    copy:
      dest: /etc/apt/apt.conf.d/99force-ipv4
      content: |
        Acquire::ForceIPv4 "true";
  roles:
    - oefenweb.postfix
    - geerlingguy.github-users
  vars:
    github_users:
      - name: captn3m0
        groups: sudo
      - name: jace
        groups: sudo
    # See documentation at https://galaxy.ansible.com/oefenweb/postfix
    postfix_hostname: email.speakforme.in
    postfix_mailname: email.speakforme.in
    postfix_aliases:
      - user: root
        alias: sesverified@email.speakforme.in
    postfix_relayhost: email-smtp.eu-west-1.amazonaws.com
    postfix_relaytls: true
    # AWS IAM SES credentials (not access key):
    postfix_sasl_user: "{{ses_user}}"
    postfix_sasl_password: "{{ses_password}}"